### ISSUE TITLE
Why is Pancreas proteomics data not centered at 0?

### ISSUE THREAD

**Issue by elachtara** [PayneLab/cptac#30]
Hi, I am working with the proteomics data from the package, and it appears that it is not centered at 0 like the remaining tissues.. Did you treat this data differently? Do you recommend further scaling to get it on the same scale as the others?

<img width="884" alt="Screen Shot 2022-08-10 at 10 20 58 AM" src="https://user-images.githubusercontent.com/49528110/183925341-df02a53f-c6ed-408b-8e03-4ec12b0ba614.png">

**Comment by old-rob** [comment]
Good question. This is because data generation/analysis for the 10 different cancer types data comes from different groups with their own opinions on what is best. For this particular cohort, the analysis team chose not to zero-center. Because our goal is just to serve the data, we have not adjusted this ourselves. If you would like it to be consistent, you can take the average for each protein column and subtract that average from the column.

**Comment by old-rob** [comment]
Let us know if you have any more issues or questions!

**Comment by elachtara** [comment]
Thanks for the responses, good to know!
