### ISSUE TITLE
pancan.download() not working, insufficient internet

### ISSUE THREAD

**Issue by ZhuZhuoHSPH** [PayneLab/cptac#32]
Hello, big thanks for this awesome package and nice documentation!

I can list the databases using `pc.list_datasets()` but can't download (`pc.download(dataset="PancanBrca", version="latest")`. The error message is similar to #4:

> NoInternetError: Insufficient internet. Check your internet connection. 

I'm pretty sure my internet is fine. I tried locally on my Mac and remotely on a server with the Box token. I wonder if it's related to Box authorization. I've registered a free Box account, but I'm not sure if there is anything else I need to do. 

Any help will be highly appreciated! Thank you for your time. 

Best,
Zhu

**Comment by caleb-lindgren** [comment]
Hi, thanks for your comment! Unfortunately the pancancer data is not yet fully publicly accessible. When you are trying to access it, Box is probably returning a 401 Unauthorized HTTP response, but the package isn't configured to recognize that, so it just assumes that it's a connectivity error which is why it's giving you the "Insufficient internet" message.

Transitioning the pancancer data out of embargo is one of the important next steps for the project, and we hope it will be accomplished within a month or two. We will do a new release of the package when that transition is complete, so you can watch for a new release, and at that point you should be able to access those data.

Thank you for your interest and support!

**Comment by ZhuZhuoHSPH** [comment]
Got it, thank you so much!
