### ISSUE TITLE
xlrd dependency missing

### ISSUE THREAD

**Issue by tobsecret** [PayneLab/cptac#5]
To use the Luad data, and I suspect most other datasets, one needs xlrd in the environment, which pandas can use but does not explicitly list as a dependency - because reasons. Again, not sure if this is missing in the package definitions or if it's an artifact of me pip-installing cptac into a conda environment that already has pandas.

**Comment by caleb-lindgren** [comment]
Thanks for the tip! I added that to the dependency requirements in setup.py, so it will be included in the next release. We do read Excel files with pandas, so that explains why we need the optional xlrd dependency.

Hearing about it initially, I wouldn't think your issues are coming from using pip inside an Anaconda environment. Here's my hypothesis: xlrd is included by default in the base Anaconda environment, but if you're working in a different environment and didn't clone the base environment when you created this environment, that would explain why you've been missing dependencies that other have already had. At any rate, hope it works out fine!

**Comment by tobsecret** [comment]
Aaah gotcha - yes, I make a new environment for every project to keep my dependencies separate. 
Thanks for fixing it so quickly!
